# official tutorial
# mkdocs-material: https://squidfunk.github.io/mkdocs-material/
# mkdocs: https://www.mkdocs.org/user-guide/configuration/

site_name: kube
repo_url: https://github.com/kube-rs/kube
repo_name: kube
# NB: edit uri won't work well with sync system if we don't have canonical docs in the same repo as the site
#edit_uri: edit/main/docs
edit_uri: 'https://github.com/kube-rs/website/edit/main/docs'
theme:
  icon:
    repo: fontawesome/brands/github
  name: material
  logo: favicon.png
  favicon: favicon.png
  palette:
  # dark mode
  - scheme: slate
    # use a lighter blue for banner and buttons (indigo too dark for buttons)
    primary: blue
    accent: blue
    media: "(prefers-color-scheme: dark)"
    toggle:
      icon: material/toggle-switch
      name: Switch to light mode
  # light mode
  - scheme: default
    media: "(prefers-color-scheme: light)"
    primary: indigo
    accent: light blue
    toggle:
      icon: material/toggle-switch-off-outline
      name: Switch to dark mode
  language: en
  features:
    - navigation.tabs
    #- navigation.indexes
    - navigation.sections
    - navigation.instant
    - navigation.tracking
    - navigation.prune
    - content.action.edit

# NB: Maintaining the nav list is not necessary, but is needed to reorder.
# Generated from "fd .md ." in docs/ folder.
# mkdocs serve will tell us about uncovered documents or broken links
nav:
- Information:
    Usage:
    #- index.md
    - getting-started.md
    #- quick-tutorial.md
    - changelog.md
    - features.md
    - upgrading.md
    - troubleshooting.md
    Policies:
    - security.md
    - stability.md
    - rust-version.md
    - kubernetes-version.md
    - release-process.md
    Third Party:
    - adopters.md
    - guides.md

- Controllers:
    Concepts:
    - controllers/intro.md
    - controllers/object.md
    - controllers/reconciler.md
    - controllers/application.md
    - controllers/relations.md
    - controllers/gc.md
    - controllers/schemas.md
    Advanced:
    - controllers/testing.md
    - controllers/admission.md
    - controllers/streams.md
    - controllers/generics.md
    - controllers/internals.md
    Operational:
    - controllers/observability.md
    - controllers/optimization.md
    - controllers/manifests.md
    - controllers/security.md
    - controllers/scaling.md
    - controllers/availability.md
  #- comunity.md
  #- proposal-process.md
  #- mentorship.md
  #- coding-style.md
- Crates:
  - crates/kube.md
  - crates/kube-core.md
  - crates/kube-client.md
  - crates/kube-derive.md
  - crates/kube-runtime.md

# Maybe something for the future
#- Proposals/Rejected: []
#- Proposals/Done: []
#- Proposals/Accepted: []
- Contributing:
  #- code-of-conduct.md
  - governance.md
  - maintainers.md
  - contributing.md
  - website.md
  - tools.md
  - architecture.md
- Blog:
  - blog/index.md

markdown_extensions:
  - attr_list # https://squidfunk.github.io/mkdocs-material/reference/images/
  - pymdownx.tabbed  # https://squidfunk.github.io/mkdocs-material/reference/content-tabs/
  - nl2br # newline-to-break
  - md_in_html # allow markdown within html blocks
  - toc:
      permalink: '#' # heading anchor
      slugify: !!python/name:pymdownx.slugs.uslugify
  - admonition
  - codehilite:
      guess_lang: false
      linenums: false
  - footnotes
  - abbr
  - pymdownx.snippets
  - meta
  - def_list
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist
  - pymdownx.tilde
  # mermaid diagrams
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

plugins:
  - search
  - roamlinks
    #- autolinks
  - blog
  - exclude:
      glob:
        - "*.tmp"
        - "*.pdf"
        - "*.gz"
      regex:
        - '.*\.(tmp|bin|tar)$'
copyright: ''
extra:
  generator: false
  social:
    #- icon: fontawesome/regular/bookmark
    #  link: https://kube.rs
    - icon: fontawesome/brands/rust
      link: https://docs.rs/kube
    - icon: fontawesome/brands/github
      link: https://github.com/kube-rs/kube/discussions
    #- icon: fontawesome/brands/mastodon
    #  link: https://hachyderm.io/@clux
    # better than twitter, but not really doing PR
    - icon: fontawesome/brands/discord
      link: https://discord.gg/tokio
    - icon: fontawesome/brands/linux
      link: https://www.linuxfoundation.org/legal/trademark-usage
